name: Cockpit

on:
#  push:
#    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-in-another-repo:
      uses: hcloud-infrastructure/terraform/.github/workflows/terraform.yml@main
  my_first_job:
    name: My first job
  my_second_job:
    name: My second job
