name: Simple 3 Jobs Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tf:
    name: Run terraform and deploy infrastructure on hcloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in repo
        run: ls -la

  conf_workstation:
    name: Run ansible and configure target system
    needs: run_tf  
    runs-on: ubuntu-latest
    steps:
      - name: Show OS details
        run: uname -a

      - name: Show CPU info
        run: lscpu

  conf_test:
    name: Run ansible and configure target systems
    needs: run_tf 
    runs-on: ubuntu-latest
    steps:
      - name: Check disk usage
        run: df -h

      - name: Show current date/time
        run: date
