name: Simple 3 Jobs Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  job_one:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"

  job_two:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is Job 2"

  job_three:
    name: Third Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "This is Job 3"
