name: Simple Workflow with Steps

on:
  workflow_dispatch:
  pull_request:

jobs:
  job_one:
    name: Checkout and List Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -la

  job_two:
    name: Show System Info
    runs-on: ubuntu-latest
    steps:
      - name: Print OS and CPU info
        run: |
          echo "OS info:"
          uname -a
          echo "CPU info:"
          lscpu

      - name: Print current time
        run: date

  job_three:
    name: Final Message and Disk Check
    runs-on: ubuntu-latest
    steps:
      - name: Disk usage
        run: df -h

      - name: Final message
        run: echo "All jobs executed successfully 🎉"
