name: Deploy hcloud infrastructure
on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tf:
    uses: .github/workflows/terraform.yml@main
#    uses: hcloud-infrastructure/workflow-terraform/.github/workflows/terraform.yml@main
    
  conf_workstation:
    name: Run ansible and configure target system
    needs: run_tf  
    runs-on: ubuntu-latest
    steps:
      - name: Show OS details
        run: uname -a

      - name: Show CPU info
        run: lscpu

  conf_test:
    name: Run ansible and configure target systems
    needs: run_tf 
    runs-on: ubuntu-latest
    steps:
      - name: Check disk usage
        run: df -h

      - name: Show current date/time
        run: date
